//auth
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'


//map
export const GET_OBJECTS_SUCCESS = 'GET_OBJECTS_SUCCESS'
export const GET_OBJECTS_FAILED = 'GET_OBJECTS_FAILED';

export const SET_SELECTED_ITEM_SUCCESS = 'SET_SELECTED_ITEM_SUCCESS';
export const SET_SELECTED_ITEM_FAILED = 'SET_SELECTED_ITEM_FAILED';

export const SET_FILTERS = 'SET_FILTERS';

export const SET_CITY = 'SET_CITY';

//select friend

export const SELECTED_FRIEND_SUCCESS = "SELECTED_FRIEND_SUCCESS";